"""Extract the DrawRune puzzle patterns (8x8 RGBA grids) and freeze them for the rune shuffle.

Outputs:
  - apworld/drova/data/runes.json          the 9 shuffleable pattern names (PaperChase excluded:
                                           it is a Freestyle quest drawing, not a pattern check)
  - ArchipelagoDrova/Data/RuneTable.g.cs   name -> 64 RGBA32 pixels in Unity GetPixels order
                                           (bottom-up rows), hex-encoded RRGGBBAA per pixel

The client rebuilds Texture2D objects from these pixels, so a puzzle can require any pattern
without loading the other puzzle's bundle. Pixels are copied verbatim: GUI_Window_Drawing's
CheckSuccess compares per-pixel alpha (and RGB for multi-color windows), so exactness matters.
"""
import UnityPy, glob, os, json, sys

BD = r"C:\Program Files (x86)\Steam\steamapps\common\Drova - Forsaken Kin\Drova_Data\StreamingAssets\aa\StandaloneWindows64"
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
OUT_JSON = os.path.join(REPO, "apworld", "drova", "data", "runes.json")
OUT_CS = os.path.join(REPO, "ArchipelagoDrova", "Data", "RuneTable.g.cs")

FREESTYLE = {"DrawRune_PaperChase"}

# Every pattern-check door is shuffleable: letter hints swap by sprite name, and all world-art
# hints (Auwald plates, RedTower clue stones, LunaTemple plate, and the two Räubermine boards -
# which hang ~2100 units from their doors, found in the field via ap_dumpnearby) are discrete
# sprites that get truthful overlays from gen_rune_hint_table.py + the client's RuneHintOverlay.
WORLD_ART_HINTED = set()

runes = {}
for f in sorted(glob.glob(os.path.join(BD, "*.bundle"))):
    try:
        env = UnityPy.load(f)
    except Exception:
        continue
    for o in env.objects:
        if o.type.name != "Texture2D":
            continue
        try:
            d = o.read()
        except Exception:
            continue
        name = d.m_Name
        if not name.startswith("DrawRune_") or name in runes:
            continue
        img = d.image.convert("RGBA")
        w, h = img.size
        assert (w, h) == (8, 8), f"{name}: unexpected size {w}x{h}"
        # PIL rows are top-down; Unity GetPixels/SetPixels32 order is bottom-up. Flip so the
        # stored order matches what the client feeds to SetPixels32.
        flipped = img.transpose(1)  # FLIP_TOP_BOTTOM
        px = list(flipped.getdata())
        runes[name] = "".join(f"{r:02x}{g:02x}{b:02x}{a:02x}" for r, g, b, a in px)

print("found:", sorted(runes))
expected = 10
assert len(runes) == expected, f"expected {expected} DrawRune textures, found {len(runes)}"

pool = sorted(n for n in runes if n not in FREESTYLE and n not in WORLD_ART_HINTED)
# ensure_ascii: the Räuber names contain non-ASCII; escaped output stays valid regardless of the
# platform default encoding (a cp1252 'ä' in the file breaks pkgutil's utf-8 decode).
json.dump({"runes": pool}, open(OUT_JSON, "w", encoding="utf-8"), ensure_ascii=True, indent=1)
print(f"pool: {len(pool)} -> {OUT_JSON}")

lines = [
    "// Generated by tools/extract_locations/extract_rune_masks.py. Do not edit by hand.",
    "using System.Collections.Generic;",
    "",
    "namespace ArchipelagoDrova.Data",
    "{",
    "    public static partial class RuneTable",
    "    {",
    "        /// <summary>Pattern name -> 64 RGBA32 pixels (8x8, Unity bottom-up row order),",
    "        /// hex RRGGBBAA per pixel. Copied verbatim from the game's DrawRune textures.",
    "        /// Holds every pattern-check rune, including the world-art-hinted ones that are",
    "        /// currently never shuffled, so a future pool change needs no client update.</summary>",
    "        public static readonly Dictionary<string, string> Generated = new Dictionary<string, string>",
    "        {",
]
for name in sorted(n for n in runes if n not in FREESTYLE):
    lines.append(f'            {{ "{name}", "{runes[name]}" }},')
lines += ["        };", "    }", "}", ""]
open(OUT_CS, "w", encoding="utf-8").write("\n".join(lines))
print(f"table: {len(runes) - len(FREESTYLE)} runes -> {OUT_CS}")
