from __future__ import annotations

import json
import pkgutil
from typing import TYPE_CHECKING, Any

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import DrovaWorld

# The item table is generated by tools/gen_data.py from the game's own item database and is frozen:
# ids are keyed by the game's readable id, so renaming an item can never renumber the datapackage.
# Each record is {name, id, readable_id, kind, amount, classification}.
# pkgutil.get_data, not open(): a packaged .apworld is a zip, so there is no real file to open.
ITEM_DATA: list[dict[str, Any]] = json.loads(pkgutil.get_data(__name__, "data/items.json").decode("utf-8"))

# Every item that could exist under any option combination must be in here, since this is the datapackage.
ITEM_NAME_TO_ID: dict[str, int] = {item["name"]: item["id"] for item in ITEM_DATA}
ITEM_NAME_TO_DATA: dict[str, dict[str, Any]] = {item["name"]: item for item in ITEM_DATA}

CLASSIFICATIONS = {
    # skip_balancing: the two keys rules.py references stay obtainable in-game regardless (vanilla
    # keys are never suppressed), and nothing else is logic-relevant at all, so progression balancing
    # would only shuffle these into earlier spheres at fill cost with near-zero payoff. Revisit if
    # rules ever gate a meaningful share of locations behind pool-only items.
    "progression": ItemClassification.progression_skip_balancing,
    "useful": ItemClassification.useful,
    "filler": ItemClassification.filler,
}

# --- Bonus pool ----------------------------------------------------------------------------------
# Large seeds have far more locations than distinct items, so the overflow is padded with repeatable
# "bonus" rewards. XP and LP are granted through PlayerAttributeStats (AddExperiencePoints /
# GiveLearningPoint), so any number of them is always valid; the item-based bonus names below are
# stackable consumables and animal trophies, where duplicates are equally harmless.
#
# The big tiers are capped per seed (a wall of +250 XP boosts trivialized leveling); the bulk of the
# overflow is small XP, consumable chunks and junk, drawn with BONUS_CATEGORY_WEIGHTS.

# (name, cap) - each tier appears randint(ceil(cap/2), cap) times per seed, biggest rewards first.
# The permanent stat raises (+1 Str/Dex/Mind, +5 max health) are capped at 10 each: at most +10 to
# every attribute and +50 max health per seed on top of vanilla progression.
CAPPED_BONUS_ITEMS: tuple[tuple[str, int], ...] = (
    ("Massive Experience Boost", 2),   # 1000 XP
    ("5 Learning Points", 2),
    ("1 Strength", 10),
    ("1 Dexterity", 10),
    ("1 Mind", 10),
    ("5 Max Health", 10),
    ("Experience Boost", 4),           # 250 XP
    ("2 Learning Points", 4),
    ("Large Experience Boost", 6),     # 100 XP
    ("Medium Experience Boost", 8),    # 50 XP
    ("Learning Point", 10),
)

SMALL_XP_NAMES = ("Tiny Experience Boost", "Small Experience Boost")  # 5 / 10 XP

# Animal trophies, coins and other sellable junk: filler item_ entries matched on these tokens.
_JUNK_TOKENS = ("claw", "fur", "tooth", "teeth", "feather", "stinger", "trophy", "coin")
# Substring false positives: "fur" catches the quest weapon part item_shaftofpurefury.
_JUNK_EXCLUDE = {"item_shaftofpurefury"}
# Token matching alone is not enough: the tokens also catch the RARE hunting trophies (Tooth of the
# Viper and Fanged Necklace sell for 100, Boar Skull 75, Bearskin 50 - one-per-kill proofs from
# dangerous animals), which must not be handed out repeatedly as bulk overflow. The game's own sell
# price (carried into items.json by gen_data.py) is the authored rarity signal, so junk is capped at
# common-drop prices. 15 keeps Bear Claw (20) and Luminous Skin (20) out - both are drops from
# dangerous beasts, not pocket lint (playtest call: bear claws should stay rare).
_JUNK_MAX_SELL = 15

# The XP/LP tiers exist only as capped/bulk bonus rewards; keep them out of the once-each top-ups
# so a small pool cannot hand out "Massive Experience Boost" as ordinary filler. "Learning Point"
# is not bonus-only: it stays a classified useful item as well. The LP bundles are classified
# useful (excluded locations must never hold them), the XP tiers filler.
BONUS_ONLY_NAMES = {name for name, _ in CAPPED_BONUS_ITEMS if name != "Learning Point"} | set(SMALL_XP_NAMES)

PROGRESSION_ITEM_NAMES = [item["name"] for item in ITEM_DATA if item["classification"] == "progression"]
USEFUL_ITEM_NAMES = [
    item["name"] for item in ITEM_DATA
    if item["classification"] == "useful" and item["name"] not in BONUS_ONLY_NAMES
]

# Consumable chunks: everything the generator gave a stack size (arrows, potions, food, throwables).
CONSUMABLE_CHUNK_NAMES = [
    item["name"] for item in ITEM_DATA
    if item["classification"] == "filler" and item["kind"] == "Item" and item["amount"] > 1
]
JUNK_ITEM_NAMES = [
    item["name"] for item in ITEM_DATA
    if item["classification"] == "filler" and item["kind"] == "Item" and item["amount"] == 1
    and item["readable_id"].startswith("item_")  # not recipes: recipe_hunterstrophy matches "trophy"
    and item["readable_id"] not in _JUNK_EXCLUDE
    and any(token in item["readable_id"].lower() for token in _JUNK_TOKENS)
    and item.get("sell", 0) <= _JUNK_MAX_SELL  # rare trophies stay once-each filler, never bulk
]

# (weight, names) - the bulk overflow draw. Consumables lead so long runs keep finding supplies.
BONUS_CATEGORY_WEIGHTS: tuple[tuple[int, list[str]], ...] = (
    (45, CONSUMABLE_CHUNK_NAMES),
    (30, list(SMALL_XP_NAMES)),
    (25, JUNK_ITEM_NAMES),
)

# Every name the bonus pool can produce; the overflow tests assert against this set.
BONUS_ITEM_NAMES = (
    {name for name, _ in CAPPED_BONUS_ITEMS}
    | set(SMALL_XP_NAMES)
    | set(CONSUMABLE_CHUNK_NAMES)
    | set(JUNK_ITEM_NAMES)
)

FILLER_ITEM_NAMES = [
    item["name"] for item in ITEM_DATA
    if item["classification"] == "filler" and item["name"] not in BONUS_ONLY_NAMES
]


def _names_with_prefix(*prefixes: str) -> set[str]:
    return {item["name"] for item in ITEM_DATA if item["readable_id"].startswith(prefixes)}


ITEM_NAME_GROUPS: dict[str, set[str]] = {
    "Keys": _names_with_prefix("key_", "misc_key_"),
    "Flow Abilities": _names_with_prefix("flow_"),
    "Energy Crystals": _names_with_prefix("item_energycrystal_"),
    "Weapons": _names_with_prefix("weapon_"),
    "Armor": _names_with_prefix("armor_"),
    "Helmets": _names_with_prefix("helmet_"),
    "Maps": _names_with_prefix("misc_worldmap", "misc_map_"),
    "Consumables": _names_with_prefix("cons_"),
    "Recipes": _names_with_prefix("recipe_"),
}


class DrovaItem(Item):
    game = "Drova - Forsaken Kin"


def create_item_by_name(world: DrovaWorld, name: str) -> DrovaItem:
    data = ITEM_NAME_TO_DATA[name]
    return DrovaItem(name, CLASSIFICATIONS[data["classification"]], data["id"], world.player)


# The gathering-minigame tools handed out by the start_with_tools option: the sturdy pickaxe
# Merik sells (mining) and a junk spear (spearfishing). Precollected, so they consume no locations.
START_TOOL_NAMES = ("Tool Pickaxe Silberhauer", "Weapon Spear WoodenSpear")


def create_all_items(world: DrovaWorld) -> None:
    if world.options.start_with_tools:
        for name in START_TOOL_NAMES:
            world.multiworld.push_precollected(world.create_item(name))

    # Every progression item always goes into the pool. generate_early has already guaranteed that
    # there are at least as many locations as there are progression items.
    itempool: list[Item] = [world.create_item(name) for name in PROGRESSION_ITEM_NAMES]

    # Event locations are already filled, so only unfilled locations need an item.
    number_of_unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))
    remaining = number_of_unfilled_locations - len(itempool)

    # Top up with useful items, then filler. Small location pools take a random subset of each so that
    # which weapons and consumables show up varies per seed rather than always being the alphabetical head.
    for candidates in (USEFUL_ITEM_NAMES, FILLER_ITEM_NAMES):
        if remaining <= 0:
            break
        if remaining >= len(candidates):
            chosen = candidates
        else:
            chosen = world.random.sample(candidates, remaining)
        itempool += [world.create_item(name) for name in chosen]
        remaining -= len(chosen)

    # Large pools run out of distinct items well before they run out of locations (~800 items, up
    # to ~6400 locations), so the rest is repeatable bonus rewards: a capped handful of big XP/LP
    # tiers, then weighted small XP, consumable chunks and junk.
    if remaining > 0:
        itempool += create_bonus_items(world, remaining)

    world.multiworld.itempool += itempool


def create_bonus_items(world: DrovaWorld, count: int) -> list[Item]:
    names: list[str] = []
    for name, cap in CAPPED_BONUS_ITEMS:
        if len(names) >= count:
            break
        tier_count = world.random.randint((cap + 1) // 2, cap)
        names += [name] * min(tier_count, count - len(names))
    while len(names) < count:
        names.append(random_bonus_item_name(world))
    return [world.create_item(name) for name in names]


def random_bonus_item_name(world: DrovaWorld) -> str:
    """A repeatable reward drawn by category weight. Also serves as get_filler_item_name, which AP
    core may call any number of times, so every candidate must stay valid in any quantity."""
    weights = [weight for weight, _ in BONUS_CATEGORY_WEIGHTS]
    _, names = world.random.choices(BONUS_CATEGORY_WEIGHTS, weights=weights)[0]
    return world.random.choice(names)
