from __future__ import annotations

import json
import pkgutil
from typing import TYPE_CHECKING, Any

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import DrovaWorld

# The item table is generated by tools/gen_data.py from the game's own item database and is frozen:
# ids are keyed by the game's readable id, so renaming an item can never renumber the datapackage.
# Each record is {name, id, readable_id, kind, amount, classification, sell, world_count}.
# pkgutil.get_data, not open(): a packaged .apworld is a zip, so there is no real file to open.
ITEM_DATA: list[dict[str, Any]] = json.loads(pkgutil.get_data(__name__, "data/items.json").decode("utf-8"))

# Every item that could exist under any option combination must be in here, since this is the datapackage.
ITEM_NAME_TO_ID: dict[str, int] = {item["name"]: item["id"] for item in ITEM_DATA}
ITEM_NAME_TO_DATA: dict[str, dict[str, Any]] = {item["name"]: item for item in ITEM_DATA}

CLASSIFICATIONS = {
    # skip_balancing: the two keys rules.py references stay obtainable in-game regardless (vanilla
    # keys are never suppressed), and nothing else is logic-relevant at all, so progression balancing
    # would only shuffle these into earlier spheres at fill cost with near-zero payoff. Revisit if
    # rules ever gate a meaningful share of locations behind pool-only items.
    "progression": ItemClassification.progression_skip_balancing,
    "useful": ItemClassification.useful,
    "filler": ItemClassification.filler,
}

# --- Bonus pool ----------------------------------------------------------------------------------
# Large seeds have far more locations than distinct items, so the overflow is padded with repeatable
# "bonus" rewards. XP and LP are granted through PlayerAttributeStats (AddExperiencePoints /
# GiveLearningPoint), so any number of them is always valid; the item-based bonus names below are
# cheap consumables, materials and animal parts, where duplicates are equally harmless.
#
# The big tiers are capped per seed (a wall of +250 XP boosts trivialized leveling); the bulk of the
# overflow is small XP plus ordinary world loot, drawn at the frequencies vanilla Drova itself uses
# (see REPEATABLE_LOOT below).

# (name, cap) - each tier appears randint(ceil(cap/2), cap) times per seed, biggest rewards first.
# The permanent stat raises (+1 Str/Dex/Mind, +5 max health) are capped at 10 each: at most +10 to
# every attribute and +50 max health per seed on top of vanilla progression.
CAPPED_BONUS_ITEMS: tuple[tuple[str, int], ...] = (
    ("Massive Experience Boost", 2),   # 1000 XP
    ("5 Learning Points", 2),
    ("1 Strength", 10),
    ("1 Dexterity", 10),
    ("1 Mind", 10),
    ("5 Max Health", 10),
    ("Experience Boost", 4),           # 250 XP
    ("2 Learning Points", 4),
    ("Large Experience Boost", 6),     # 100 XP
    ("Medium Experience Boost", 8),    # 50 XP
    ("Learning Point", 10),
)

SMALL_XP_NAMES = ("Tiny Experience Boost", "Small Experience Boost")  # 5 / 10 XP

# Substring false positive of the old token matching, still excluded by name: "fur" catches the
# quest weapon part item_shaftofpurefury.
_JUNK_EXCLUDE = {"item_shaftofpurefury"}

# Repeats are capped by price on top of the frequency weights below. Weights already make expensive
# things rare, but an item worth 50 handed out even a hundred times over a 6000-location seed is a
# money printer, and the rare hunting trophies (Tooth of the Viper 100, Boar Skull 75, Bearskin 50)
# are one-per-kill proofs that should stay once-each filler. 30 also keeps the tier-1 potions
# (Health 50, Flow 40) and the gemstones out of the bulk draw, which is the point of this pass.
_BULK_MAX_SELL = 30

# The XP/LP tiers exist only as capped/bulk bonus rewards; keep them out of the once-each top-ups
# so a small pool cannot hand out "Massive Experience Boost" as ordinary filler. "Learning Point"
# is not bonus-only: it stays a classified useful item as well. The LP bundles are classified
# useful (excluded locations must never hold them), the XP tiers filler.
BONUS_ONLY_NAMES = {name for name, _ in CAPPED_BONUS_ITEMS if name != "Learning Point"} | set(SMALL_XP_NAMES)

PROGRESSION_ITEM_NAMES = [item["name"] for item in ITEM_DATA if item["classification"] == "progression"]
USEFUL_ITEM_NAMES = [
    item["name"] for item in ITEM_DATA
    if item["classification"] == "useful" and item["name"] not in BONUS_ONLY_NAMES
]

# --- The bulk draw: Drova's own loot frequencies ---------------------------------------------------
# tools/extract_locations/extract_loot_distribution.py counts how often a full vanilla sweep of the
# map hands the player each item - world pickups, destroyable vases and boxes, mining/herb/fishing
# spots and authored container slots - and gen_data.py freezes that as `world_count`.
#
# The overflow used to be drawn uniformly inside two hand-written categories, which threw away every
# bit of that: a 5x stack of Health Potion 1 (12 finds in the whole game) was exactly as likely as
# Berries (144) or Callashrooms (206), and half the things Drova actually litters the map with -
# logs, apples, ore, feathers - could never appear at all, because a stack size of 1 and no junk
# token kept them out of both lists. Weighting the draw by world_count is the game's own answer to
# "how common is this", and it is what makes long seeds read like Drova instead of like a potion shop.
#
# Eligibility: filler only (gear, keys and maps are useful/progression and stay once-each), something
# the world actually drops, and cheap enough to repeat. Only three id prefixes are filler AND dropped
# by the world - item_ (consumables, food, materials, animal parts), cons_ (single-use flow scrolls,
# harmless in any quantity) and recipe_. Recipes are the one exclusion: a recipe is learned once, so
# every copy after the first is dead weight.
#
# Cooked food is the exception to "something the world drops". Fishpan, Fogstew, Rootstew and the rest
# are recipe outputs the player makes at a fire, so they never appear as loot and world_count is 0 -
# which would freeze every one of them at a single pool copy, exactly the "cooked food shows up once"
# complaint. They are ordinary consumables you eat constantly, so gen_data flags them (cooked_food)
# and they get a flat nominal weight instead: rarer than the natural staples the world litters
# (apple/berry weigh 90-200), but a real repeatable presence rather than one-and-done. The price cap
# does not apply to them - a 28-gold cooked meal is food you make, not the rare treasure or tier-1
# potion the cap exists to keep from flooding the pool.
NOMINAL_COOKED_FOOD_WEIGHT = 12.0


def _repeat_weight(item: dict[str, Any]) -> float:
    """Overflow draw weight for one item, or 0 to exclude it. world_count is how often vanilla hands
    the item over; cooked food substitutes a nominal floor because the world never drops it."""
    if item["classification"] != "filler" or item["kind"] != "Item":
        return 0.0
    if item["readable_id"].startswith("recipe_") or item["readable_id"] in _JUNK_EXCLUDE:
        return 0.0
    world = float(item.get("world_count", 0))
    if item.get("cooked_food"):
        return max(world, NOMINAL_COOKED_FOOD_WEIGHT)
    if world <= 0 or item.get("sell", 0) > _BULK_MAX_SELL:
        return 0.0
    return world


REPEATABLE_LOOT: tuple[tuple[str, float], ...] = tuple(
    (item["name"], w) for item in ITEM_DATA for w in (_repeat_weight(item),) if w > 0
)
REPEATABLE_LOOT_NAMES = [name for name, _ in REPEATABLE_LOOT]
REPEATABLE_LOOT_WEIGHTS = [weight for _, weight in REPEATABLE_LOOT]

# Percent of the bulk overflow that is world loot; the rest is small XP. Keeping a fixed XP share
# (rather than folding XP into the weights) is what stops a 6000-location seed from being 100%
# mushrooms - the previous split was 45 consumables + 25 junk + 30 XP, so the loot share is unchanged.
LOOT_DRAW_PERCENT = 70

# --- Quest supply ----------------------------------------------------------------------------------
# Quests ask for ordinary things: logs for Jendrik's woodpile, silver ore through the whole prologue,
# mushrooms for "Missing", a torch to get into the deep mine. None of it is quest-flagged, so with
# suppress_vanilla_loot the world stops handing it over and the pool becomes the only source. One
# copy each - which is all the once-each filler pass gives - is not a supply: "bring me ten logs"
# needs ten. gen_data.py marks these items with `quest_supply` (extracted from the item references
# in the game's own quest and dialogue graphs), and the overflow seeds a working stock of each
# before it starts drawing at random.
#
# The floor deliberately ignores every rule the bulk draw lives by. Those rules exist to keep the
# overflow feeling like Drova - a price cap so repeats cannot print money, a world_count weight so
# rare things stay rare - and all three would silently starve exactly the items a quest needs:
#   * Mandragora sells for 100, so the price cap barred it from repeating at all;
#   * Basaltroot, Hawthorne, Cliff Lichen, Brainfood Plant and Luminous Bass are permanent stat
#     herbs, classified useful, and useful items never repeat;
#   * Ruin Blossom's only trace in the graphs is an ambient-looking dialogue name.
# A quest asking for seven of something does not care that it is expensive or rare.
#
# Gear on the list (the mine escape's spear, Chunnaic's armour parts) needs no floor: it is wanted
# once and the once-each pass already places it. Anything that stacks gets its floor in UNITS, so
# the option means the same thing whether an item is granted one or five at a time.
# gen_data.py splits the flagged items into supply groups, each sized by its own option: ten logs and
# nine permanent +1 Strength herbs are not the same decision, and Mandragora is a 100-gold root whose
# vanilla count testers wanted to match. (name, units-per-grant, group).
QUEST_SUPPLY_ITEMS: tuple[tuple[str, int, str], ...] = tuple(
    (item["name"], max(item["amount"], 1), item.get("supply_group") or "quest")
    for item in ITEM_DATA if item.get("quest_supply")
)
QUEST_SUPPLY_NAMES = {name for name, _, _ in QUEST_SUPPLY_ITEMS}

SUPPLY_GROUP_OPTIONS = {
    "quest": "quest_item_supply",
    "permanent_herb": "permanent_herb_supply",
    "mandragora": "mandragora_supply",
}


def quest_supply_copies(world: DrovaWorld) -> list[tuple[str, int]]:
    """(name, copies) for the guaranteed floor, each group sized by its own option. The option is in
    UNITS, so it means the same thing whether an item is granted one or five at a time."""
    copies: list[tuple[str, int]] = []
    for name, amount, group in QUEST_SUPPLY_ITEMS:
        units = getattr(world.options, SUPPLY_GROUP_OPTIONS.get(group, "quest_item_supply")).value
        if units:
            copies.append((name, -(-units // amount)))
    return copies

# Every name the bonus pool can produce; the overflow tests assert against this set.
BONUS_ITEM_NAMES = (
    {name for name, _ in CAPPED_BONUS_ITEMS}
    | set(SMALL_XP_NAMES)
    | set(REPEATABLE_LOOT_NAMES)
    | QUEST_SUPPLY_NAMES
)

FILLER_ITEM_NAMES = [
    item["name"] for item in ITEM_DATA
    if item["classification"] == "filler" and item["name"] not in BONUS_ONLY_NAMES
]


def _names_with_prefix(*prefixes: str) -> set[str]:
    return {item["name"] for item in ITEM_DATA if item["readable_id"].startswith(prefixes)}


ITEM_NAME_GROUPS: dict[str, set[str]] = {
    "Keys": _names_with_prefix("key_", "misc_key_"),
    "Flow Abilities": _names_with_prefix("flow_"),
    "Energy Crystals": _names_with_prefix("item_energycrystal_"),
    "Weapons": _names_with_prefix("weapon_"),
    "Armor": _names_with_prefix("armor_"),
    "Helmets": _names_with_prefix("helmet_"),
    "Maps": _names_with_prefix("misc_worldmap", "misc_map_"),
    "Consumables": _names_with_prefix("cons_"),
    "Recipes": _names_with_prefix("recipe_"),
}


class DrovaItem(Item):
    game = "Drova - Forsaken Kin"


def create_item_by_name(world: DrovaWorld, name: str) -> DrovaItem:
    data = ITEM_NAME_TO_DATA[name]
    return DrovaItem(name, CLASSIFICATIONS[data["classification"]], data["id"], world.player)


# The gathering-minigame tools handed out by the start_with_tools option: the sturdy pickaxe
# Merik sells (mining) and a junk spear (spearfishing). Precollected, so they consume no locations.
START_TOOL_NAMES = ("Tool Pickaxe Silberhauer", "Weapon Spear WoodenSpear")


def create_all_items(world: DrovaWorld) -> None:
    if world.options.start_with_tools:
        for name in START_TOOL_NAMES:
            world.multiworld.push_precollected(world.create_item(name))

    # Every progression item always goes into the pool. generate_early has already guaranteed that
    # there are at least as many locations as there are progression items.
    itempool: list[Item] = [world.create_item(name) for name in PROGRESSION_ITEM_NAMES]

    # Event locations are already filled, so only unfilled locations need an item.
    number_of_unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))
    remaining = number_of_unfilled_locations - len(itempool)

    # Top up with useful items, then filler. Small location pools take a random subset of each so that
    # which weapons and consumables show up varies per seed rather than always being the alphabetical head.
    for candidates in (USEFUL_ITEM_NAMES, FILLER_ITEM_NAMES):
        if remaining <= 0:
            break
        if remaining >= len(candidates):
            chosen = candidates
        else:
            chosen = world.random.sample(candidates, remaining)
        itempool += [world.create_item(name) for name in chosen]
        remaining -= len(chosen)

    # Large pools run out of distinct items well before they run out of locations (~800 items, up
    # to ~6400 locations), so the rest is repeatable bonus rewards: a capped handful of big XP/LP
    # tiers, then small XP and world loot drawn at Drova's own frequencies.
    if remaining > 0:
        itempool += create_bonus_items(world, remaining)

    world.multiworld.itempool += itempool


def create_bonus_items(world: DrovaWorld, count: int) -> list[Item]:
    names: list[str] = []
    # Quest supply first: whatever else the overflow turns into, the seed contains enough of the
    # things a quest can ask the player to hand over. The once-each filler pass has already placed
    # one of each, so these are the copies on top of it.
    for name, copies in quest_supply_copies(world):
        if len(names) >= count:
            break
        names += [name] * min(copies, count - len(names))
    for name, cap in CAPPED_BONUS_ITEMS:
        if len(names) >= count:
            break
        tier_count = world.random.randint((cap + 1) // 2, cap)
        names += [name] * min(tier_count, count - len(names))
    while len(names) < count:
        names.append(random_bonus_item_name(world))
    return [world.create_item(name) for name in names]


def random_bonus_item_name(world: DrovaWorld) -> str:
    """A repeatable reward: world loot drawn at Drova's own frequencies, or a small XP boost. Also
    serves as get_filler_item_name, which AP core may call any number of times, so every candidate
    must stay valid in any quantity."""
    if REPEATABLE_LOOT_NAMES and world.random.randrange(100) < LOOT_DRAW_PERCENT:
        return world.random.choices(REPEATABLE_LOOT_NAMES, weights=REPEATABLE_LOOT_WEIGHTS)[0]
    return world.random.choice(SMALL_XP_NAMES)
