from __future__ import annotations

import json
import pkgutil
from typing import TYPE_CHECKING, Any

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import DrovaWorld

# The item table is generated by tools/gen_data.py from the game's own item database and is frozen:
# ids are keyed by the game's readable id, so renaming an item can never renumber the datapackage.
# Each record is {name, id, readable_id, kind, amount, classification}.
# pkgutil.get_data, not open(): a packaged .apworld is a zip, so there is no real file to open.
ITEM_DATA: list[dict[str, Any]] = json.loads(pkgutil.get_data(__name__, "data/items.json").decode("utf-8"))

# Every item that could exist under any option combination must be in here, since this is the datapackage.
ITEM_NAME_TO_ID: dict[str, int] = {item["name"]: item["id"] for item in ITEM_DATA}
ITEM_NAME_TO_DATA: dict[str, dict[str, Any]] = {item["name"]: item for item in ITEM_DATA}

CLASSIFICATIONS = {
    # skip_balancing: the two keys rules.py references stay obtainable in-game regardless (vanilla
    # keys are never suppressed), and nothing else is logic-relevant at all, so progression balancing
    # would only shuffle these into earlier spheres at fill cost with near-zero payoff. Revisit if
    # rules ever gate a meaningful share of locations behind pool-only items.
    "progression": ItemClassification.progression_skip_balancing,
    "useful": ItemClassification.useful,
    "filler": ItemClassification.filler,
}

# Experience Boost is granted through PlayerAttributeStats.AddExperiencePoints, so it is infinitely
# repeatable and never dead: any amount of it is always a valid item.
FILLER_ITEM_NAME = "Experience Boost"

PROGRESSION_ITEM_NAMES = [item["name"] for item in ITEM_DATA if item["classification"] == "progression"]
USEFUL_ITEM_NAMES = [item["name"] for item in ITEM_DATA if item["classification"] == "useful"]
FILLER_ITEM_NAMES = [item["name"] for item in ITEM_DATA if item["classification"] == "filler"]


def _names_with_prefix(*prefixes: str) -> set[str]:
    return {item["name"] for item in ITEM_DATA if item["readable_id"].startswith(prefixes)}


ITEM_NAME_GROUPS: dict[str, set[str]] = {
    "Keys": _names_with_prefix("key_", "misc_key_"),
    "Flow Abilities": _names_with_prefix("flow_"),
    "Energy Crystals": _names_with_prefix("item_energycrystal_"),
    "Weapons": _names_with_prefix("weapon_"),
    "Armor": _names_with_prefix("armor_"),
    "Helmets": _names_with_prefix("helmet_"),
    "Maps": _names_with_prefix("misc_worldmap", "misc_map_"),
    "Consumables": _names_with_prefix("cons_"),
    "Recipes": _names_with_prefix("recipe_"),
}


class DrovaItem(Item):
    game = "Drova - Forsaken Kin"


def create_item_by_name(world: DrovaWorld, name: str) -> DrovaItem:
    data = ITEM_NAME_TO_DATA[name]
    return DrovaItem(name, CLASSIFICATIONS[data["classification"]], data["id"], world.player)


def create_all_items(world: DrovaWorld) -> None:
    # Every progression item always goes into the pool. generate_early has already guaranteed that
    # there are at least as many locations as there are progression items.
    itempool: list[Item] = [world.create_item(name) for name in PROGRESSION_ITEM_NAMES]

    # Event locations are already filled, so only unfilled locations need an item.
    number_of_unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))
    remaining = number_of_unfilled_locations - len(itempool)

    # Top up with useful items, then filler. Small location pools take a random subset of each so that
    # which weapons and consumables show up varies per seed rather than always being the alphabetical head.
    for candidates in (USEFUL_ITEM_NAMES, FILLER_ITEM_NAMES):
        if remaining <= 0:
            break
        if remaining >= len(candidates):
            chosen = candidates
        else:
            chosen = world.random.sample(candidates, remaining)
        itempool += [world.create_item(name) for name in chosen]
        remaining -= len(chosen)

    # Large pools run out of distinct items well before they run out of locations (805 items, up to
    # 5055 locations), so the rest is repeatable filler.
    itempool += [world.create_filler() for _ in range(remaining)]

    world.multiworld.itempool += itempool
