from __future__ import annotations

import json
import pkgutil
from typing import TYPE_CHECKING, Any

from BaseClasses import Location, LocationProgressType

from . import items, regions

if TYPE_CHECKING:
    from .options import DrovaOptions
    from .world import DrovaWorld

# The location table is generated by tools/gen_data.py from the game's scene bundles and is frozen:
# container ids are keyed by GuidComponent guid and quest ids by the quest's stable key, so renaming a
# location can never renumber the datapackage.
# Each record is {name, id, key, kind, category, area, classification} plus faction/quest_name on quests.
# pkgutil.get_data, not open(): a packaged .apworld is a zip, so there is no real file to open.
LOCATION_DATA: list[dict[str, Any]] = json.loads(
    pkgutil.get_data(__name__, "data/locations.json").decode("utf-8")
)

# Every location that could exist under any option combination must be in here, since this is the
# datapackage. Which ones a given seed actually creates is decided in create_all_locations.
LOCATION_NAME_TO_ID: dict[str, int] = {location["name"]: location["id"] for location in LOCATION_DATA}

# ~6400 locations is far too many for one seed, so each category is a separate toggle.
CATEGORY_TO_OPTION = {
    "Chest": "randomize_chests",
    "Container": "randomize_containers",
    "Quest": "randomize_quests",
    "Critter": "randomize_critters",
    "Resource": "randomize_resources",
    "Cache": "randomize_caches",
    "Pickup": "randomize_pickups",
    "Trader": "randomize_traders",
    "Mugging": "randomize_muggings",
}

GOAL_LOCATION_NAME = "Escape Drova"
VICTORY_ITEM_NAME = "Victory"

# Synthetic milestone locations. Not in CATEGORY_TO_OPTION: they are count-gated by a Range
# option, not by a toggle, and they have no world object (the client sends them from persisted
# counters: kills, attribute points bought at teachers, talents learned).
KILL_MILESTONE_CATEGORY = "KillMilestone"
KILL_MILESTONE_GROUP = "Enemy Kills"

# category -> (option attribute, group name)
COUNT_GATED_CATEGORIES = {
    KILL_MILESTONE_CATEGORY: ("enemy_kill_checks", KILL_MILESTONE_GROUP),
    "AttributeMilestone": ("attribute_learn_checks", "Attributes Learned"),
    "TalentMilestone": ("talent_learn_checks", "Talents Learned"),
}

TRADER_CATEGORY = "Trader"
TRADER_GROUP = "Traders"

MUGGING_CATEGORY = "Mugging"
MUGGING_GROUP = "Muggings"

# The named areas containers were resolved to. Everything else falls back to regions.WILDS_REGION.
AREA_REGIONS = sorted(
    {
        location["area"]
        for location in LOCATION_DATA
        if location["kind"] != "Quest" and regions.region_for_area(location["area"]) != regions.WILDS_REGION
    }
)


class DrovaLocation(Location):
    game = "Drova - Forsaken Kin"


def _location_name_groups() -> dict[str, set[str]]:
    groups: dict[str, set[str]] = {}
    for location in LOCATION_DATA:
        if location["kind"] == "Quest":
            group = "Quests"
        elif location["category"] in COUNT_GATED_CATEGORIES:
            group = COUNT_GATED_CATEGORIES[location["category"]][1]
        elif location["category"] == TRADER_CATEGORY:
            group = TRADER_GROUP
        elif location["category"] == MUGGING_CATEGORY:
            group = MUGGING_GROUP
        else:
            group = regions.region_for_area(location["area"])
        groups.setdefault(group, set()).add(location["name"])
    return groups


LOCATION_NAME_GROUPS = _location_name_groups()


def enabled_location_data(options: DrovaOptions) -> list[dict[str, Any]]:
    """The location records this seed will actually create.

    Callable from generate_early, before any region or location object exists, so that the option
    guards can report a bad combination before generation gets further.
    """
    faction = options.faction.current_key
    enabled: list[dict[str, Any]] = []
    for location in LOCATION_DATA:
        # Milestone categories are count-gated, not toggle-gated: only the first N exist per seed.
        if location["category"] in COUNT_GATED_CATEGORIES:
            option_name = COUNT_GATED_CATEGORIES[location["category"]][0]
            if location["milestone"] <= getattr(options, option_name).value:
                enabled.append(location)
            continue
        if not getattr(options, CATEGORY_TO_OPTION[location["category"]]):
            continue
        # Joining a faction locks the other's questline and its merchants, so those locations can
        # never be reached. Quests and traders carry a faction; everything else is neutral.
        # Muggings are the exception: an opposite-faction NPC may still be reachable (their camp is
        # only partly locked), so they stay in the pool and are EXCLUDED instead (see
        # create_regular_locations) - nothing valuable can land on them.
        if (
            location.get("faction", "neutral") not in ("neutral", faction)
            and location["category"] != MUGGING_CATEGORY
        ):
            continue
        enabled.append(location)
    return enabled


def create_all_locations(world: DrovaWorld) -> None:
    create_regular_locations(world)
    create_events(world)


def create_regular_locations(world: DrovaWorld) -> None:
    faction = world.options.faction.current_key
    by_region: dict[str, dict[str, int | None]] = {}
    excluded_names: list[str] = []
    for location in enabled_location_data(world.options):
        # Quests happen all over the map, and milestone counters are not spatial at all, so both
        # live in the hub.
        if location["kind"] == "Quest" or location["category"] in COUNT_GATED_CATEGORIES:
            region_name = regions.HUB_REGION
        else:
            region_name = regions.region_for_area(location["area"])
        by_region.setdefault(region_name, {})[location["name"]] = location["id"]
        # Opposite-faction NPCs may be partly or fully unreachable, so their muggings must never
        # hold progression or useful items.
        if (
            location["category"] == MUGGING_CATEGORY
            and location.get("faction", "neutral") not in ("neutral", faction)
        ):
            excluded_names.append(location["name"])

    for region_name, region_locations in by_region.items():
        world.get_region(region_name).add_locations(region_locations, DrovaLocation)

    for name in excluded_names:
        world.get_location(name).progress_type = LocationProgressType.EXCLUDED


def create_events(world: DrovaWorld) -> None:
    # The goal event exists for LOGIC ONLY. Beating the game is reported to the server by the client
    # sending a StatusUpdate (session.SetGoalAchieved), never by this location being "checked".
    world.get_region(regions.HUB_REGION).add_event(
        GOAL_LOCATION_NAME, VICTORY_ITEM_NAME, location_type=DrovaLocation, item_type=items.DrovaItem
    )
