using Drova_Modding_API.GlobalFields;

namespace ArchipelagoDrova.Data
{
    public enum GrantKind
    {
        Item,
        Talent,
        Xp,
        LearningPoint,
        Attribute,
        MaxHealth
    }

    /// <summary>
    /// How one Archipelago item name is applied to the game.
    /// <see cref="Key"/> is a Drova item readable id for <see cref="GrantKind.Item"/>,
    /// a talent container guid for <see cref="GrantKind.Talent"/>, the attribute name
    /// ("strength" / "dexterity" / "mind") for <see cref="GrantKind.Attribute"/>, and unused otherwise.
    /// </summary>
    public readonly struct ItemGrant
    {
        public readonly GrantKind Kind;
        public readonly string Key;
        public readonly int Amount;

        public ItemGrant(GrantKind kind, string key, int amount)
        {
            Kind = kind;
            Key = key;
            Amount = amount;
        }

        public static ItemGrant Item(string readableId)
        {
            return new ItemGrant(GrantKind.Item, readableId, 1);
        }

        public static ItemGrant Item(string readableId, int amount)
        {
            return new ItemGrant(GrantKind.Item, readableId, amount);
        }

        public static ItemGrant Talent(string talentGuid)
        {
            return new ItemGrant(GrantKind.Talent, talentGuid, 1);
        }

        public static ItemGrant Xp(int amount)
        {
            return new ItemGrant(GrantKind.Xp, "", amount);
        }

        public static ItemGrant LearningPoint(int amount)
        {
            return new ItemGrant(GrantKind.LearningPoint, "", amount);
        }
    }

    /// <summary>
    /// AP item name -> grant action. Keys must match ItemInfo.ItemName exactly.
    /// The contents live in ItemTable.g.cs, generated by tools/gen_data.py from the same
    /// source as the apworld's items.json so the two can never drift.
    /// An AP item name missing from this table is logged once and skipped.
    /// </summary>
    public static partial class ItemTable
    {
        /// <summary>
        /// A property, NOT a static field initialized from Generated.
        /// Generated lives in the other half of this partial class (ItemTable.g.cs), and C# does not
        /// define the order of static field initializers across partial files. With ItemTable.cs
        /// listed first in the csproj, a field initializer here captured Generated while it was still
        /// null, so every lookup threw a NullReferenceException. Resolving on access avoids the
        /// ordering question entirely. LocationTable reads its generated tables lazily for the same
        /// reason, which is why container lookups worked and item lookups did not.
        /// </summary>
        public static Dictionary<string, ItemGrant> Items
        {
            get { return Generated; }
        }
    }
}
