using UnityEngine;

namespace ArchipelagoDrova.Data
{
    /// <summary>
    /// Overlay geometry for one piece of rune hint art (a riddle plate or clue stone): where the
    /// pattern grid sits inside the sprite, which part of the pattern it shows, the art's ON/OFF
    /// cell colors, and an alpha mask so overlays follow broken plate edges. Region coordinates
    /// are sprite-rect pixels with a bottom-left origin; the mask is row-major bottom-up.
    /// </summary>
    public readonly struct RuneHintPiece
    {
        public readonly string Pattern;
        /// <summary>"full" for an 8x8 plate, or the pattern quadrant a 4x4 clue displays.</summary>
        public readonly string Quad;
        public readonly int Cells;
        public readonly float CellSize;
        public readonly int X;
        public readonly int Y;
        public readonly int W;
        public readonly int H;
        /// <summary>Image-space to sprite-rect-space correction: the atlas trims the plate art
        /// (e.g. 72x72 rect packs 67x67 content at ~(2.1, 3.1)), and the runtime pivot lives in
        /// rect space, so overlay positions must add this. Includes the fit's sub-pixel part.</summary>
        public readonly float OffsetX;
        public readonly float OffsetY;
        public readonly Color32 OnColor;
        public readonly Color32 OffColor;
        public readonly string MaskHex;

        public RuneHintPiece(string pattern, string quad, int cells, float cellSize,
            int x, int y, int w, int h, float offsetX, float offsetY,
            Color32 onColor, Color32 offColor, string maskHex)
        {
            Pattern = pattern;
            Quad = quad;
            Cells = cells;
            CellSize = cellSize;
            X = x;
            Y = y;
            W = w;
            H = h;
            OffsetX = offsetX;
            OffsetY = offsetY;
            OnColor = onColor;
            OffColor = offColor;
            MaskHex = maskHex;
        }

        /// <summary>Is the mask opaque at region-local (x, y bottom-up)?</summary>
        public bool MaskAt(int x, int y)
        {
            int index = y * W + x;
            char c = MaskHex[index / 4];
            int nibble = c <= '9' ? c - '0' : char.ToLowerInvariant(c) - 'a' + 10;
            return (nibble & (1 << (3 - index % 4))) != 0;
        }
    }

    /// <summary>
    /// Hint-art sprite name -> overlay geometry. Generated by
    /// tools/extract_locations/gen_rune_hint_table.py, which calibrates the grid inside each art
    /// piece against the known vanilla pattern and refuses to emit fits below 97% agreement.
    /// </summary>
    public static partial class RuneHintTable
    {
    }
}
