using UnityEngine;

namespace ArchipelagoDrova.Data
{
    /// <summary>
    /// The rune-drawing puzzle patterns (8x8 pixel grids), copied verbatim from the game's
    /// DrawRune_* textures. The contents live in RuneTable.g.cs, generated by
    /// tools/extract_locations/extract_rune_masks.py from the same extraction as the apworld's
    /// runes.json so the two can never drift.
    /// </summary>
    public static partial class RuneTable
    {
        /// <summary>
        /// Decode one entry into 64 RGBA32 pixels in Unity's bottom-up SetPixels32 order.
        /// Returns null for unknown names.
        /// </summary>
        public static Color32[] DecodePixels(string runeName)
        {
            if (!Generated.TryGetValue(runeName, out string hex) || hex.Length != 64 * 8)
            {
                return null;
            }

            var pixels = new Color32[64];
            for (int i = 0; i < 64; i++)
            {
                int o = i * 8;
                pixels[i] = new Color32(ParseByte(hex, o), ParseByte(hex, o + 2), ParseByte(hex, o + 4), ParseByte(hex, o + 6));
            }
            return pixels;
        }

        private static byte ParseByte(string hex, int offset)
        {
            return (byte)(Nibble(hex[offset]) << 4 | Nibble(hex[offset + 1]));
        }

        private static int Nibble(char c)
        {
            if (c >= '0' && c <= '9')
            {
                return c - '0';
            }
            return char.ToLowerInvariant(c) - 'a' + 10;
        }
    }
}
