// Generated by tools/extract_locations/gen_rune_hint_scenes.py. Do not edit by hand.
using System;
using System.Collections.Generic;

namespace ArchipelagoDrova.Data
{
    public static partial class RuneHintTable
    {
        /// <summary>Streamed scenes that contain rune hint art. Scene loads outside this
        /// set are skipped without touching a single renderer - chunk scenes stream in
        /// constantly while walking and sweeping them all cost visible frame drops.</summary>
        public static readonly HashSet<string> HintScenes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "Scene_Overworld_Environment_19_11", // RuneDrawRiddleClue_RedTower_NE, RuneDrawRiddleClue_RedTower_NW, RuneDrawRiddleClue_RedTower_SE, RuneDrawRiddleClue_RedTower_SW
            "Scene_Overworld_Interaction_0_38", // Ruin_Riddle_Plates_0, Ruin_Riddle_Plates_1, Ruin_Riddle_Plates_2, Ruin_Riddle_Plates_3
            "Scene_Overworld_Interaction_14_37", // Ruin_Riddle_Plates_Räubermine_0, Ruin_Riddle_Plates_Räubermine_1
            "Scene_Overworld_Interaction_20_31", // Ruin_Riddle_Plates_LunaTemple
        };
    }
}
