namespace ArchipelagoDrova.Data
{
    /// <summary>
    /// One shuffleable gate's vanilla link: the gate it pairs with and the exact arrival point
    /// (position + walk-out direction) its OW_Teleporter sends the player to. The arrival point is
    /// an authored anchor a few units beside the partner gate, so remapping copies these values
    /// verbatim rather than deriving anything from gate positions.
    /// </summary>
    public readonly struct TeleporterGate
    {
        public readonly string Partner;
        public readonly float TargetX;
        public readonly float TargetY;
        public readonly float TargetDirX;
        public readonly float TargetDirY;

        public TeleporterGate(string partner, float targetX, float targetY, float targetDirX, float targetDirY)
        {
            Partner = partner;
            TargetX = targetX;
            TargetY = targetY;
            TargetDirX = targetDirX;
            TargetDirY = targetDirY;
        }
    }

    /// <summary>
    /// Gate name (the OW_Teleporter GameObject's name, unique in the scene) -> vanilla link data,
    /// for exactly the gates in the apworld's shuffle pool. The contents live in
    /// TeleporterTable.g.cs, generated by tools/extract_locations/gen_teleporter_pairs.py from the
    /// same extraction as the apworld's teleporters.json so the two can never drift.
    /// </summary>
    public static partial class TeleporterTable
    {
    }
}
