using ArchipelagoDrova.Data;
using Il2CppDrova.Saveables;
using UnityEngine;

namespace ArchipelagoDrova
{
    /// <summary>
    /// The progress table (opened from the F7 panel): checked/total per area and per check category,
    /// computed from the live
    /// session (server truth, so remote collects count too). Location names are generated by
    /// tools/gen_data.py in fixed shapes ("Area - Chest 12 - Item 2", "Quest - Title", "Trader -
    /// Name - Item", "Enemy Kills - 5"), so the breakdown is parsed from the names instead of
    /// shipping a second table. The row of the area the player is currently in is highlighted
    /// yellow, resolved from the save's PlayerAreaLocaKey via the generated AreaKeyToName map.
    /// </summary>
    public class ApProgressPanel(ArchipelagoClient client)
    {
        private struct Cell
        {
            public int Checked;
            public int Total;
        }

        /// <summary>Fixed display order; columns a seed does not use are hidden.</summary>
        private static readonly string[] ColumnOrder =
            ["Chest", "Container", "Quest", "Pickup", "Cache", "Resource", "Critter", "Trader", "Mugging",
             "Kills", "Attributes", "Talents"];

        // area -> category -> cell, rebuilt only when the server-side checked count moves.
        private readonly Dictionary<string, Dictionary<string, Cell>> _byArea = new();
        private readonly List<string> _areaOrder = [];
        private readonly List<string> _columns = [];
        private int _builtAtCheckedCount = -1;
        private bool _builtWhileConnected;

        private string _currentArea = "";
        private float _nextAreaPollAt;

        public void Draw()
        {
            EnsureBuilt();

            if (!_builtWhileConnected || _areaOrder.Count == 0)
            {
                var empty = new Rect(20f, 290f, 320f, 48f);
                GUI.Box(empty, "Archipelago Progress");
                GUI.Label(new Rect(empty.x + 10f, empty.y + 24f, empty.width - 20f, 20f),
                    client.Connected ? "No location data yet." : "Not connected.");
                return;
            }

            const float labelWidth = 190f;
            const float columnWidth = 86f;
            const float rowHeight = 19f;

            // With one column the per-row total repeats it; with one area the grand row repeats it.
            bool showTotalColumn = _columns.Count > 1;
            bool showGrandRow = _areaOrder.Count > 1;

            float width = 20f + labelWidth + columnWidth * (_columns.Count + (showTotalColumn ? 1 : 0));
            float height = 30f + rowHeight * (_areaOrder.Count + 1 + (showGrandRow ? 1 : 0));
            var panel = new Rect(20f, 290f, width, height);
            GUI.Box(panel, "Archipelago Progress");

            float x = panel.x + 10f;
            float y = panel.y + 24f;

            GUI.Label(new Rect(x, y, labelWidth, rowHeight), "Area");
            float cx = x + labelWidth;
            for (int i = 0; i < _columns.Count; i++)
            {
                GUI.Label(new Rect(cx, y, columnWidth, rowHeight), _columns[i]);
                cx += columnWidth;
            }
            if (showTotalColumn)
            {
                GUI.Label(new Rect(cx, y, columnWidth, rowHeight), "Total");
            }
            y += rowHeight;

            if (Time.realtimeSinceStartup >= _nextAreaPollAt)
            {
                _currentArea = CurrentAreaDisplay();
                _nextAreaPollAt = Time.realtimeSinceStartup + 1f;
            }

            var grand = new Dictionary<string, Cell>();
            foreach (string area in _areaOrder)
            {
                DrawRow(area, _byArea[area], x, y, labelWidth, columnWidth, rowHeight, showTotalColumn,
                    highlight: area == _currentArea);
                Accumulate(grand, _byArea[area]);
                y += rowHeight;
            }
            if (showGrandRow)
            {
                DrawRow("Everything", grand, x, y, labelWidth, columnWidth, rowHeight, showTotalColumn);
            }
        }

        /// <summary>
        /// The display name of the area the player is in, or "" when unknown. PlayerAreaLocaKey is
        /// the save's own record, written whenever the player enters an AreaName volume - out in the
        /// unnamed wilds it keeps the last named area, so the highlight is the best effort there.
        /// </summary>
        private static string CurrentAreaDisplay()
        {
            try
            {
                var save = Savegame.Current;
                if (save == null || save.Data == null)
                {
                    return "";
                }
                // An extension in the game's code; the interop surfaces it as plain static.
                string key = Il2Cpp.SavegameDataExtensions.GetPlayerAreaLocaKey(save.Data);
                return string.IsNullOrEmpty(key) ? "" : LocationTable.AreaKeyToName.GetValueOrDefault(key, "");
            }
            catch
            {
                // The save is not up yet (main menu, loading). No highlight is the right answer.
                return "";
            }
        }

        private void DrawRow(string label, Dictionary<string, Cell> cells,
            float x, float y, float labelWidth, float columnWidth, float rowHeight, bool showTotalColumn,
            bool highlight = false)
        {
            var previousColor = GUI.color;
            if (highlight)
            {
                GUI.color = Color.yellow;
            }
            GUI.Label(new Rect(x, y, labelWidth, rowHeight), highlight ? "> " + label : label);
            GUI.color = previousColor;
            float cx = x + labelWidth;
            var rowTotal = new Cell();
            for (int i = 0; i < _columns.Count; i++)
            {
                if (cells.TryGetValue(_columns[i], out var cell) && cell.Total > 0)
                {
                    DrawCell(cell, cx, y, columnWidth, rowHeight);
                    rowTotal.Checked += cell.Checked;
                    rowTotal.Total += cell.Total;
                }
                else
                {
                    GUI.Label(new Rect(cx, y, columnWidth, rowHeight), "-");
                }
                cx += columnWidth;
            }
            if (showTotalColumn)
            {
                DrawCell(rowTotal, cx, y, columnWidth, rowHeight);
            }
        }

        private static void DrawCell(Cell cell, float x, float y, float width, float height)
        {
            var previous = GUI.color;
            if (cell.Total > 0 && cell.Checked >= cell.Total)
            {
                GUI.color = Color.green;
            }
            GUI.Label(new Rect(x, y, width, height), cell.Checked + "/" + cell.Total);
            GUI.color = previous;
        }

        private static void Accumulate(Dictionary<string, Cell> into, Dictionary<string, Cell> row)
        {
            foreach (var pair in row)
            {
                into.TryGetValue(pair.Key, out var cell);
                cell.Checked += pair.Value.Checked;
                cell.Total += pair.Value.Total;
                into[pair.Key] = cell;
            }
        }

        private void EnsureBuilt()
        {
            // LocationsChecked is server truth and only ever grows within a room; a reconnection to a
            // different room resets it, and the connected flag covers the disconnect state.
            if (_builtWhileConnected == client.Connected && _builtAtCheckedCount == client.LocationsChecked)
            {
                return;
            }

            _byArea.Clear();
            _areaOrder.Clear();
            _columns.Clear();
            _builtWhileConnected = client.Connected;
            _builtAtCheckedCount = client.LocationsChecked;

            var states = client.GetSeedLocationStates();
            foreach (var state in states)
            {
                Classify(state.Key, out string area, out string category);

                if (!_byArea.TryGetValue(area, out var cells))
                {
                    cells = new Dictionary<string, Cell>();
                    _byArea[area] = cells;
                    _areaOrder.Add(area);
                }
                cells.TryGetValue(category, out var cell);
                cell.Total++;
                if (state.Value)
                {
                    cell.Checked++;
                }
                cells[category] = cell;
            }

            _areaOrder.Sort(StringComparer.Ordinal);
            foreach (string column in ColumnOrder)
            {
                if (ColumnUsed(column))
                {
                    _columns.Add(column);
                }
            }
            // Anything the fixed order does not know (a future category) still gets a column.
            foreach (var cells in _byArea.Values)
            {
                foreach (string category in cells.Keys)
                {
                    if (!_columns.Contains(category))
                    {
                        _columns.Add(category);
                    }
                }
            }
        }

        private bool ColumnUsed(string category)
        {
            foreach (var cells in _byArea.Values)
            {
                if (cells.ContainsKey(category))
                {
                    return true;
                }
            }
            return false;
        }

        private static void Classify(string name, out string area, out string category)
        {
            if (name.StartsWith("Quest - ", StringComparison.Ordinal))
            {
                area = "Quests";
                category = "Quest";
                return;
            }
            if (name.StartsWith("Trader - ", StringComparison.Ordinal))
            {
                area = "Traders";
                category = "Trader";
                return;
            }
            if (name.StartsWith("Enemy Kills - ", StringComparison.Ordinal))
            {
                area = "Enemy Kills";
                category = "Kills";
                return;
            }
            if (name.StartsWith("Mugging - ", StringComparison.Ordinal))
            {
                area = "Muggings";
                category = "Mugging";
                return;
            }
            if (name.StartsWith("Attributes Learned - ", StringComparison.Ordinal))
            {
                area = "Teacher Learning";
                category = "Attributes";
                return;
            }
            if (name.StartsWith("Talents Learned - ", StringComparison.Ordinal))
            {
                area = "Teacher Learning";
                category = "Talents";
                return;
            }

            int separator = name.IndexOf(" - ", StringComparison.Ordinal);
            if (separator <= 0)
            {
                area = "Other";
                category = "Other";
                return;
            }

            area = name[..separator];
            // ~95 chunk-coordinate pseudo areas would drown the table; collapse them like regions.py.
            if (area.StartsWith("Wilds ", StringComparison.Ordinal))
            {
                area = "The Wilds";
            }

            string rest = name[(separator + 3)..];
            int space = rest.IndexOf(' ');
            category = space > 0 ? rest[..space] : rest;
        }
    }
}
